### ISSUE TITLE
Latest updates have failed to load

### ISSUE THREAD

**Issue by grantclem** [zweckj/acaia#8]
In the past 24 hours or so, both updates have failed to load

```
2024-11-11 07:24:28.458 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Acaia Scale for acaia
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 635, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/acaia/__init__.py", line 14, in async_setup_entry
    coordinator = AcaiaCoordinator(hass, entry)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/acaia/coordinator.py", line 45, in __init__
    self._scale = AcaiaScale(
                  ^^^^^^^^^^^
TypeError: AcaiaScale.__init__() got an unexpected keyword argument 'mac'
```

**Comment by zweckj** [comment]
@grantclem apologies, hopefully fixed by 0.3.4
